version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=Spellbook
      - MYSQL_USER=m-dro
      - MYSQL_PASSWORD=123456 

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/site/
    ports:
      - "8000:8000"
    depends_on:
      - db
    